kind: Pod
apiVersion: v1
metadata:
  name: flipkart
spec:
  containers:
    - name: sample1
      image: ubuntu
      command: ["/bin/bash", "-c" , "while true; do echo 'Devops Kubernetes'; sleep 5; done"]
