kind: ReplicationController
apiVersion: v1
metadata:
  name: backup
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: abc
      labels:
        app: nginx
    spec:
      containers:
        - name: xyz
          image: nginx
          ports:
            - containerPort: 80


