kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: testyentra
spec:
  replicas: 2
  selector:
    matchExpressions:
      - { key: myname, operator: In, values: [qspiders, jspiders, pyspiders]}
      - { key: env, operator: NotIn, values: [skillrary]}
  template:
    metadata:
      name: abc
      labels:
        myname: qspiders
    spec:
      containers:
        - name: xyz
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo 'Hello-Word'; sleep 3; done"]


